inherit_mode:
  merge:
    - Exclude
    - Include

AllCops:
  TargetRubyVersion: 2.5


#############################################
# Layout
#

Layout/HashAlignment:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table
  EnforcedLastArgumentHashStyle: ignore_implicit
  SupportedLastArgumentHashStyles: ignore_implicit

Layout/EmptyLinesAroundClassBody:
  EnforcedStyle: empty_lines

Layout/EmptyLinesAroundModuleBody:
  EnforcedStyle: empty_lines_except_namespace

Layout/SpaceBeforeBlockBraces:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/SpaceAroundMethodCallOperator:
  Enabled: true

Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true

Layout/BeginEndAlignment:
  Enabled: true

#############################################
# Style
#

Style/DefWithParentheses:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/MethodDefParentheses:
  Enabled: false

Style/Encoding:
  Enabled: false

Style/SingleLineBlockParams:
  Enabled: false

Style/EmptyCaseCondition:
  Enabled: false

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%': '""'
    '%i': '[]'
    '%q': "''"
    '%Q': '""'
    '%r': '()'
    '%s': '[]'
    '%w': '[]'
    '%W': '[]'
    '%x': '()'

Style/SignalException:
  EnforcedStyle: only_raise

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

Style/AccessModifierDeclarations:
  Enabled: true

Style/ExponentialNotation:
  Enabled: true

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/SlicingWithRange:
  Enabled: true

Style/RedundantRegexpCharacterClass:
  Enabled: true

Style/RedundantRegexpEscape:
  Enabled: true

Style/AccessorGrouping:
  Enabled: true

Style/BisectedAttrAccessor:
  Enabled: true

Style/RedundantAssignment:
  Enabled: true

Style/RedundantFetchBlock:
  Enabled: true

Style/ArrayCoercion:
  Enabled: true

Style/CaseLikeIf:
  Enabled: true

Style/HashAsLastArrayItem:
  Enabled: true

Style/HashLikeCase:
  Enabled: true

Style/RedundantFileExtensionInRequire:
  Enabled: true

Style/ExplicitBlockArgument:
  Enabled: true

Style/GlobalStdStream:
  Enabled: true

Style/OptionalBooleanParameter:
  Enabled: true

Style/SingleArgumentDig:
  Enabled: true

Style/StringConcatenation:
  Enabled: true

Style/CombinableLoops:
  Enabled: true

Style/KeywordParametersOrder:
  Enabled: true

Style/RedundantSelfAssignment:
  Enabled: true

Style/SoleNestedConditional:
  Enabled: true

Style/ClassEqualityComparison:
  Enabled: true

Style/ArgumentsForwarding:
  Enabled: true

Style/CollectionCompact:
  Enabled: true

Style/DocumentDynamicEvalDefinition:
  Enabled: true

Style/NegatedIfElseCondition:
  Enabled: true

Style/SwapValues:
  Enabled: true

Style/NilLambda:
  Enabled: true

#############################################
# Naming
#

Naming/PredicateName:
  ForbiddenPrefixes:
    - is_
    - has_
    - have_
    - the_
    - a_
    - should_

Naming/VariableNumber:
  EnforcedStyle: snake_case

Naming/VariableName:
  Enabled: true

Naming/FileName:
  Exclude:
    - 'Gemfile'
    - 'Guardfile'

#############################################
# Metrics
#

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*_spec.rb'
    - 'spec/spec_helper.rb'
    - 'spec/factories/**/*.rb'
    - 'spec/support/shared_examples/*.rb'

Layout/LineLength:
  Exclude:
    - 'spec/**/*'
  Max: 140
  AllowURI: true

#############################################
# Security
#

Security/Eval:
  Enabled: true

Security/MarshalLoad:
  Enabled: true


#############################################
# Lint
#

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Lint/DeprecatedOpenSSLConstant:
  Enabled: true

Lint/MixedRegexpCaptureTypes:
  Enabled: true

Lint/DuplicateElsifCondition:
  Enabled: true

Lint/AssignmentInCondition:
  Enabled: true
  AllowSafeAssignment: false

Lint/BinaryOperatorWithIdenticalOperands:
  Enabled: true

Lint/DuplicateRescueException:
  Enabled: true

Lint/EmptyConditionalBody:
  Enabled: true

Lint/FloatComparison:
  Enabled: true

Lint/MissingSuper:
  Enabled: true

Lint/OutOfRangeRegexpRef:
  Enabled: true

Lint/SelfAssignment:
  Enabled: true

Lint/TopLevelReturnWithArgument:
  Enabled: true

Lint/UnreachableLoop:
  Enabled: true

Lint/DuplicateRequire:
  Enabled: true

Lint/EmptyFile:
  Enabled: true

Lint/TrailingCommaInAttributeDeclaration:
  Enabled: true

Lint/UselessMethodDefinition:
  Enabled: true

Lint/ConstantDefinitionInBlock:
  Enabled: false

Lint/IdentityComparison:
  Enabled: true

Lint/UselessTimes:
  Enabled: true

Lint/HashCompareByIdentity:
  Enabled: true

Lint/RedundantSafeNavigation:
  Enabled: true

Lint/DuplicateRegexpCharacterClassElement:
  Enabled: true

Lint/EmptyBlock:
  Enabled: true

Lint/NoReturnInBeginEndBlocks:
  Enabled: true

Lint/ToEnumArguments:
  Enabled: true

Lint/UnmodifiedReduceAccumulator:
  Enabled: true

Lint/DuplicateBranch:
  Enabled: true

Lint/EmptyClass:
  Enabled: true


#############################################
# Performance
#

Performance/AncestorsInclude:
  Enabled: true

Performance/BigDecimalWithNumericArgument:
  Enabled: true

Performance/RedundantSortBlock:
  Enabled: true

Performance/RedundantStringChars:
  Enabled: true

Performance/ReverseFirst:
  Enabled: true

Performance/SortReverse:
  Enabled: true

Performance/Squeeze:
  Enabled: true

Performance/StringInclude:
  Enabled: true

Performance/Sum:
  Enabled: true

Performance/ArraySemiInfiniteRangeSlice:
  Enabled: true

Performance/BlockGivenWithExplicitBlock:
  Enabled: true

Performance/CollectionLiteralInLoop:
  Enabled: true

Performance/ConstantRegexp:
  Enabled: true

Performance/MethodObjectAsBlock:
  Enabled: true
